### ISSUE TITLE
Generate QR codes and/or bar codes

### ISSUE THREAD

**Issue by berniyh** [monich/sailfish-barcode#3]
afaik there is currently no app for sailfish to generate codes.
It might be an interesting idea to integrate such functionality into CodeReader, I'd certainly appreciate it. :)

Oh and thanks for this awesome app. ;)

**Comment by Olf0** [comment]
BTW, there actually is a SailfishOS-native app for generating barcodes: https://openrepos.net/content/ade/clubcode-fork

**Comment by monich** [comment]
Now that scanned images are saved, many barcodes can be scanned back from the saved image (although not all and the fact that they are damaged by detection marks doesn't help).

What kind of use case do you have in mind? I'm not sure if such a functionality belongs to this app since its purpose is to do exactly the opposite - scan the barcode.

**Comment by Olf0** [comment]
Well, if bar- and QR-code generation "belongs" integrated into a bar- and QR-code scanning app is a matter of definition.  There are many examples for one or the other approach.

@berniyh, my comment yesterday was primarily aimed at you, to inform you that there is a SailfishOS-native app for generating barcodes (contrary to your original assessment).

IMHO having the scanning and generating function in a single app is at most "nice to have" for users, but not worth any effort implementing that, as these functions are already available in two independent apps.
Hence, @monich, I did not have any use case for having both functions in a single app in mind when writing [yesterday's comment](https://github.com/monich/sailfish-barcode/issues/3#issuecomment-483467978), and @berniyh's [original issue report](https://github.com/monich/sailfish-barcode/issues/3#issue-337276699) sounds as if he simply was not aware of [Clubcode](https://openrepos.net/content/ade/clubcode-fork) or the functionality it provides (its name is a bit misleading, IMO).
From my perspective this issue is rather a non-issue.

**Comment by berniyh** [comment]
Thanks for the note. Indeed, I was not aware that clubcode exists, mainly due to the fact that I don't use openrepos.
However, for me it's barely usable, as my main focus is on QR codes, I use them to quickly transfer data (e.g. links, text passages, sometimes even passwords) between devices (desktop, tablet, phone) without requiring (or possibly wanting) to transfer the data over the network.
For 1D barcodes, I don't really have a use, since they can't be used except for very simple strings.

You're right that it is questionable if a code reader should also be a code generator.
My main motivation for the suggestion was that:
a) I didn't think that it exists
b) I thought that some portion of the code might be reused since you already handle barcodes/QR codes for the decoding case.

Of course you may disagree here and deny the suggestion.

**Comment by Olf0** [comment]
Well then (understanding your use case, now), maybe suggesting to @a-dekker to [extend Clubcode to also generate QR-codes](https://github.com/a-dekker/ClubCode/issues) is a technically easier approach.

P.S.: And I assume that either maintainer (@monich and @a-dekker) is open to code contributions (e.g. per pull request) to Codereader rsp. Clubcode.

**Comment by a-dekker** [comment]
Don't expect QR-code support in the ClubCode app: https://openrepos.net/comment/28343#comment-28343

**Comment by monich** [comment]
QR-codes are quite simple to generate with https://github.com/fukuchi/libqrencode. This is how it's done in my FoilAuth in case if anyone is interested:

https://github.com/monich/harbour-foilauth/blob/master/src/FoilAuthToken.cpp#L223
https://github.com/monich/harbour-foilauth/blob/master/src/QrCodeImageProvider.cpp#L41

**Comment by berniyh** [comment]
> P.S.: And I assume that either maintainer (@monich and @a-dekker) is open to code contributions (e.g. per pull request) to Codereader rsp. Clubcode.
I would need an environment I could generate and test the apps with, which I do not have.

> Don't expect QR-code support in the ClubCode app: https://openrepos.net/comment/28343#comment-28343
Yeah, I read that, hence I didn't really think any further about ClubCode.

> QR-codes are quite simple to generate with https://github.com/fukuchi/libqrencode. This is how it's done in my FoilAuth in case if anyone is interested:
libqrencode is also what my desktop (Plasma/KDE frameworks, which has a library named prison for code generation) uses and it's working like charm.

**Comment by monich** [comment]
I have added QR code generation functionality to my Foil Notes app:

https://github.com/monich/harbour-foilnotes/commit/e1b625b

It's included in version 1.0.9, available in both Jolla Store (soon) and OpenRepos (already).

**Comment by Olf0** [comment]
Thanks @monich, technically this is working fine with FoilNotes 1.0.9 (installed from OpenRepos, decoding generated QR-code with CodeReader).
Side note: That really looks surprisingly [easy to implement](https://github.com/monich/harbour-foilnotes/commit/e1b625b).

But it is really awkward to use:
- I failed to find the function to generate QR-codes in FoilNotes, until I looked up aforementioned commit (to understand that it is offered in the top pulley when viewing an encrypted note).
- Having to create an encrypted note in order to generate a barcode from its content is quite a detour, when simply generating a QR-code from the clipboard content is the goal.
- BTW, wouldn't it make sense to allow for generating QR-codes from unencrypted notes in FoilNotes, too (i.e., to also offer that pulley entry there)?

So while it is nice to have gained the ability to generate QR-codes with a SailfishOS native app, looking at the user experience / workflow I concur with @berniyh that this functionality should rather be added to CodeReader or ClubCode.

**Comment by monich** [comment]
FoilNotes is supposed to generate QR codes for both encrypted and plain text notes.

**Comment by berniyh** [comment]
Thanks monich, I'll surely try it out once the version hits the store.

While I don't have a need for another note app (let alone one that encrypts notes) it's still much better this way than having to install some random android code generator (which btw crashed all the time).

I'd still support adding this to sailfish-barcode (since I think it makes sense to keep handling the barcodes in one app), but I can also understand why you chose to add it to foilnotes.

**Comment by Olf0** [comment]
> FoilNotes is supposed to generate QR codes for both encrypted and plain text notes.

Checked again: Yes, they do.
Sorry, I have no idea how I got the opposite impression on my other phone, initially.

**Comment by a-dekker** [comment]
Working on an implementation in ClubCode, thanks for the direction.

**Comment by monich** [comment]
And I came up with https://github.com/monich/harbour-qrclip, not sure how useful it going to be though.

**Comment by berniyh** [comment]
Nice, you rock! :)

I think with these 3 apps, you and @a-dekker (if he finalized the integration into ClubCode) have now covered pretty much any use case I could come up with, so feel free to close this one. I'm satisfied with what is available.

btw, I love QR clip. It's small, simple and easy to use. Don't need more than that.

**Comment by a-dekker** [comment]
It's already implemented in ClubCode, even before harbour-qrclip was released :-)

**Comment by monich** [comment]
I guess we can close this issue then!

**Comment by monich** [comment]
And one more way to do more or less the same thing: https://github.com/monich/sailfish-qrshare :) Closing
